  levels = {
    [1] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "w....h.....w...w",
      "w....h........hw",
      "w....h.w...w..hw",
      "w..r.h..rr...hkw",
      "w....h........hw",
      "w..h.h.........w",
      "w....h.........w",
      "w....h...p.....w",
      "w....h.........w",
      "w....h.........w",
      "w....w.....w...w",
      "w....h.........w",
      "w.d..h.........w",
      "wwwwwwwwwwwwwwww"
    },
    [2] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "wh...hh....w...w",
      "w..h.hhw...w...w",
      "w..r.hh.rr.....w",
      "w....hh..h.....w",
      "w..h.hh.....h..w",
      "w....hhh...hkh.w",
      "w....hh.h...h..w",
      "w....hh..h.....w",
      "w....hh.p.h....w",
      "w....hhrr..h...w",
      "w....wh....wh..w",
      "w....hh......h.w",
      "w.d..hh.......hw",
      "wwwwwwwwwwwwwwww"
    },
    [3] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "wkhhh..........w",
      "wwwwww.hhhhh...w",
      "w.....hr.r.rh..w",
      "w.r...h.r.r.h..w",
      "w......hhhhh...w",
      "w..............w",
      "w.h............w",
      "wwhhwwwwwwwwwwww",
      "ww..........r..w",
      "w.hhh..........w",
      "w.....r.....h..w",
      "w....rrr.......w",
      "w......p.....wdw",
      "wwwwwwwwwwwwwwww"
    },
    [4] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "wrhrhrhrhrhrhhhd",
      "whrhrhrhrhrhrhrw",
      "wrhrhrhrhrhrhrhw",
      "whrhrhrhrhrhrhrw",
      "whrhr.rhr.rhrhrw",
      "wrhrhr.r.rhrhrhw",
      "whrhr.rpr.rhrhrw",
      "wrhrhrhr.rhrhrhw",
      "whrhrhrhrhrhrhrw",
      "wrhrhrhrhrhrhrhw",
      "whrhr.rhrhrhrhrw",
      "wrkrhrhrhrhrhrhw",
      "whrhrhrhrhrhrhrw",
      "wwwwwwwwwwwwwwww"
    },
    [5] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "w.rp...........w",
      "wwwwwwwww......w",
      "wdwk..hww......w",
      "whw..h.ww......w",
      "w.w.hrhww..r...w",
      "w.whrrrwwhhhhhhw",
      "w.w.hrhww......w",
      "w.wh.h.ww......w",
      "w.w.h.hww......w",
      "w.wh.h.ww......w",
      "whw.r.rww......w",
      "w.hr.r.hh......w",
      "w.h....hhr.r.r.w",
      "wwwwwwwwwwwwwwww"
    },
    [6] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "w..............w",
      "w.......ccc....w",
      "w......wwcww...w",
      "w.....w..c..w..w",
      "w.....w.....w..w",
      "w.....w..p..w..w",
      "w......w.d.w...w",
      "w.......www....w",
      "w..............w",
      "wccccccccccccccw",
      "w.............cw",
      "w.r.r.r.r.r.rckw",
      "w.............cw",
      "wwwwwwwwwwwwwwww"
    },
    [7] = {
      zoom = 2,
      "wwwwwwww",
      "w....hdw",
      "wcrcrcrw",
      "wr.c.c.w",
      "w..r..hw",
      "wp...hkw",
      "wwwwwwww"
    },
    [8] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "wdw....h.....h.w",
      "whrhc..h..hh.h.w",
      "wpcrhc.h..kh.h.w",
      "wwwcrhrh.h.h.h.w",
      "wllwcrhh.......w",
      "wlllwcrh.......w",
      "wlgllwcrhhchchcw",
      "wllgllwcrrrrrrrw",
      "wllllllww.r.r.cw",
      "w..............w",
      "w..............w",
      "w..............w",
      "w..............w",
      "wwwwwwwwwwwwwwww"
    },
    [9] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "wp.............w",
      "w..r..rrrr..r..w",
      "w..cccccwcccc..w",
      "w..hhhwwhhwwh..w",
      "w..hcccccccch..w",
      "w..h.rcwcwwch..w",
      "w.whr.rkcwdhhw.w",
      "w..h.rcwwwwch..w",
      "w..hcccccccch..w",
      "w..hwhwhhwhhw..w",
      "w..cccccccccc..w",
      "w..r..rrrr..r..w",
      "w..............w",
      "wwwwwwwwwwwwwwww"
    },
    [10] = {
      zoom = 2,
      "wwwwwwww",
      "wkhhhhdw",
      "wwr.ccww",
      "w..rc..w",
      "w.rrrwww",
      "w.....pw",
      "wwwwwwww"
    },
    [11] = {
      zoom = 2,
      "wwwwwwww",
      "wglglglw",
      "wlglglgw",
      "wp.bk.dw",
      "wglglglw",
      "wlglglgw",
      "wwwwwwww"
    },
    [12] = {
        "wwwwwwwwwwwwwwww",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhdhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "w.........>>>vww",
        "wp....r.ccwwwhdw",
        "w.......ck<<<<ww",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "wwwwwwwwwwwwwwww"
    },
    [13] = {
        "wwwwwwwwwwwwwwww",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "w^^^^^V<<<<<<hhw",
        "w^^^^^Vkcwww^r.w",
        "w<<<<<<crr.r..pw",
        "wwwwdwwcc.r.c..w",
        "whhhhhhhhcccchhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "whhhhhhhhhhhhhhw",
        "wwwwwwwwwwwwwwww"
    },
    [14] = {
      zoom = 1,
      "wwwwwwwwwwwwwwww",
      "wp>>>>>>>>>>>..w",
      "wwwwwwwwwwwwwr.w",
      "w.......r.r....w",
      "w...crr.r.hr..rw",
      "w....hcchh..r.vw",
      "w.r.chchchchr.vw",
      "w.r.h.w.w..c.r<w",
      "w...c.wkww.hw..w",
      "w...h.wwdwwcw..w",
      "w.r.c.hhccchw..w",
      "w...hchchchcw..w",
      "w...wwwwwwwww..w",
      "w..............w",
      "wwwwwwwwwwwwwwww"
    },